SC-4925: Registration doesn`t work in the demo mode if ssl is equal true
spryker/docker-sdk pull request #151
Opened 2020-09-19 12:55 UTC by zyuzka

### Description

- Ticket/Issue: https://spryker.atlassian.net/browse/SC-4925

#### Change log

- added default value for `SPRYKER_XDEBUG_MODE_ENABLE`

### Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2020-09-22 05:56 UTC, alexanderM91 approved these changes

2020-09-24 00:27 UTC, sprymiker requested changes
These changes are not complete. It will break debug or set debug mode regardless -x flag.

2020-09-25 07:41 UTC, sprymiker approved these changes

2020-09-25 07:41 UTC, alexanderM91 approved these changes

2020-09-28 06:35 UTC, merged