TE-7283: Replaced PhantomJS with Chromedriver for testing mode
spryker/docker-sdk pull request #153
Opened 2020-09-25 09:48 UTC by bezpiatovs

### Description

- Ticket/Issue: https://spryker.atlassian.net/browse/TE-7283

Replace PhantomJS that is End-Of-Life with new Chromedriver engine running Chromium for tests.

#### Related resources

https://github.com/spryker/suite-nonsplit/pull/4601
https://github.com/spryker/spryker/pull/7570

#### Change log

- Replaced `PhantomJS` docker image with `Chromedriver` to use `Chromium` as default testing browser.

### Checklist
- [x] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2020-09-28 08:13 UTC, alexanderM91 approved these changes

2020-09-29 07:28 UTC, zyuzka approved these changes

2020-10-07 09:24 UTC, zyuzka approved these changes

2020-10-17 09:53 UTC, sprymiker requested changes
Service must be added in the table in README.md

2020-10-21 12:16 UTC, sprymiker approved these changes

2020-10-22 13:32 UTC, merged