Import existing prerequisites and installation docs
spryker/docker-sdk pull request #160
Opened 2020-11-24 07:52 UTC by andriitserkovnyi

### Description

- Ticket/Issue: https://spryker.atlassian.net/browse/SC-5307

docker/sdk installation docs

#### Related resources

#### Change log

import existing docs

### Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2020-12-14 15:06 UTC, zyuzka requested changes

2020-12-14 15:06 UTC, zyuzka commented on docs/06-installation/02-installation-guides/02-installation-guide-development-mode.md
> +@(Info)()(If needed, add corresponding entries for other stores. For example, if you are going to have a US store, add the following entries: `zed.us.spryker.local glue.us.spryker.local yves.us.demo-
same

2020-12-16 08:05 UTC, andriitserkovnyi commented on docs/06-installation/01-installation-prerequisites/02-linux-installation-prerequisites.md
> +```
Do you mean that the reader can optionally follow the instructions in the article you've linked?

2020-12-16 08:10 UTC, andriitserkovnyi commented on docs/06-installation/02-installation-guides/01-modes-overview.md
> +docker/sdk {run|start|up} -x
Please suggest your changes directly :)

2020-12-16 14:54 UTC, zyuzka commented on docs/06-installation/01-installation-prerequisites/02-linux-installation-prerequisites.md
> +```
By default, you can use docker with `sudo` only.
Those steps provide your user into the `docker` group

2020-12-16 14:58 UTC, zyuzka commented on docs/06-installation/02-installation-guides/01-modes-overview.md
> +docker/sdk {run|start|up} -x
```suggestion
docker/sdk {run|start|up|cli} -x
```

2020-12-16 15:04 UTC, zyuzka commented on docs/06-installation/02-installation-guides/01-modes-overview.md
> +Learn more about the solutions in respective documentation:
mutagen link

2020-12-24 08:25 UTC, zyuzka approved these changes

2021-01-13 09:38 UTC, merged