SC-7676: Deploy file inheritance and templating
spryker/docker-sdk pull request #250
Opened 2021-10-18 08:09 UTC by zyuzka

### Description

- Ticket/Issue: https://spryker.atlassian.net/browse/SC-7676
- RG: https://release.spryker.com/release-groups/view/3914

#### Related resources

- Nonsplit: https://github.com/spryker/suite-nonsplit/pull/6071

#### Change log

- Introduced deploy file inheritance and templating. 

### Checklist
- [x] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2021-11-29 12:21 UTC, alexanderM91 requested changes

2021-11-29 12:21 UTC, alexanderM91 commented on generator/deploy-file-generator/src/Command/ConfigCommand.php
> +use DeployFileGenerator\DeployFileFactory;
Please rename to DeployFileGenerator

2021-11-29 12:21 UTC, alexanderM91 commented on generator/deploy-file-generator/config/validation.yml
> +groups.*.region:
Should we check that database is required?
I can assume docker/sdk will fail. Could you please recheck?

2021-11-29 12:21 UTC, alexanderM91 commented on generator/deploy-file-generator/config/validation.yml
> +groups.*.applications.*.application:
Should it be required?

2021-11-29 12:21 UTC, alexanderM91 commented on generator/deploy-file-generator/config/validation.yml
> +services.*.engine:
Should an engine be required?

2021-11-29 12:21 UTC, alexanderM91 commented on generator/deploy-file-generator/src/Command/ConfigCommand.php
> +                ->createValidationTableOutput()
Is it required to build table output? Can we replace it with foreach?

2021-11-29 12:21 UTC, alexanderM91 commented on generator/deploy-file-generator/src/Cleaner/Cleaner.php
> +namespace DeployFileGenerator\Cleaner;
Let's re-structure our executors per stages.
As far as I see we have pre, executors and post.

2021-11-29 12:23 UTC, alexanderM91 commented on generator/deploy-file-generator/src/DeployFileConfig.php
> +class DeployFileConfig
DeployFileGeneratorConfig?

2021-11-29 12:23 UTC, alexanderM91 commented on generator/deploy-file-generator/src/DeployFileFactory.php
> +class DeployFileFactory
DeployFileGeneratorFactory?

2021-11-29 12:24 UTC, alexanderM91 commented on generator/deploy-file-generator/src/Executor/CleanUpExecutor.php
> +class CleanUpExecutor implements ExecutorInterface
Can be omitted as it's an executor (post)

2021-11-29 12:28 UTC, alexanderM91 commented on generator/deploy-file-generator/src/Validator/ValidatorFactory.php
> +class ValidatorFactory
DeployFileValidatorFactory?

2021-11-29 12:28 UTC, alexanderM91 commented on generator/phpstan.neon
> +    level: 6
Should we remove it?

2021-11-29 12:32 UTC, alexanderM91 commented on generator/tests/unit/DeployFileGeneratorTest/Importer/YamlDataImporterTest.php
> +namespace Unit\DeployFileGeneratorTest\Importer;
// Act
// Arrange
// Asset

2021-11-29 14:56 UTC, zyuzka commented on generator/tests/_support/Helper/Unit.php
> +class Unit extends \Codeception\Module
Nope. Codecept doesn't generate these helpers

2021-11-29 14:57 UTC, zyuzka commented on generator/deploy-file-generator/config/validation.yml
> +groups.*.region:
Added

2021-11-29 14:57 UTC, zyuzka commented on generator/deploy-file-generator/config/validation.yml
> +groups.*.applications.*.application:
added

2021-11-29 15:29 UTC, zyuzka commented on generator/deploy-file-generator/config/validation.yml
> +services.*.engine:
Should be

2021-11-29 15:30 UTC, zyuzka commented on generator/deploy-file-generator/src/Command/ConfigCommand.php
> +                ->createValidationTableOutput()
Added DeployFileOutput

2021-11-30 12:23 UTC, alexanderM91 commented on generator/deploy-file-generator/config/validation.yml
> +groups.*.applications.*.endpoints:
Is it possible to setup an application without defined endpoints?

2021-11-30 12:56 UTC, alexanderM91 commented on generator/deploy-file-generator/src/DeployFileGeneratorFactory.php
> +            $this->createDeployFileConfig()->getProjectDirectoryPath(),
Maybe it's better to use the whole config object instead of specific property?

2021-11-30 12:56 UTC, alexanderM91 commented on generator/deploy-file-generator/tests/unit/DeployFileGeneratorTest/DeployFileGeneratorFactoryTest.php
> +class DeployFileGeneratorFactoryTest extends Unit
What does this test check?

2021-11-30 12:56 UTC, alexanderM91 commented on generator/deploy-file-generator/tests/unit.suite.yml
> +    step_decorators: ~
An empty line.

2021-11-30 12:58 UTC, alexanderM91 commented on docs/07-deploy-file/01-deploy-file.md
> +Deploy file is a [Docker Compose](https://docs.docker.com/compose/) YAML file used by the Docker SDK to build infrastructure for applications. The deploy file's structure is based on [YAML version 1.
I am not sure that it's docker-compose

2021-11-30 13:05 UTC, alexanderM91 commented on docs/07-deploy-file/01-deploy-file.md
> +Deploy file is a [Docker Compose](https://docs.docker.com/compose/) YAML file used by the Docker SDK to build infrastructure for applications. The deploy file's structure is based on [YAML version 1.
Based on Deploy file we generated docker-composer file which describes application services.

2021-11-30 13:08 UTC, zyuzka commented on docs/07-deploy-file/01-deploy-file.md
> +Deploy file is a [Docker Compose](https://docs.docker.com/compose/) YAML file used by the Docker SDK to build infrastructure for applications. The deploy file's structure is based on [YAML version 1.
@andriitserkovnyi

2021-11-30 13:29 UTC, alexanderM91 requested changes

2021-11-30 13:29 UTC, alexanderM91 commented on docs/07-deploy-file/01-deploy-file.md
> +Usual deploy file have duplicate section or section has a small different.
During deployment or development process you run into the duplication of the deploy file sections or they have minor difference, like different domain name or stores configuration.
For avoiding it you probably will create an additional deploy file with the required changes.

2021-11-30 13:29 UTC, alexanderM91 commented on docs/07-deploy-file/01-deploy-file.md
> +The [`imports:`](02-deploy.file.reference.v1.md#imports) deploy file parameter is used to add additional deploy files to a build.
Can we start, e.g to avoid the current case you can use imports:, which works like ...

2021-11-30 13:29 UTC, alexanderM91 commented on docs/07-deploy-file/01-deploy-file.md
> +When an application with multiple deploy files is being built, a deploy file builder parses and merges the deploy files into a single one at `/{DOCKER_SDK_DIRECTORY}/deployment/default/project.yml`.
Can we combine both sentences into the one, like during the build it vies for these folders in the specific priority and after this a new project.yml generated.
Also, it will be useful to add an example.

2021-11-30 13:29 UTC, alexanderM91 commented on docs/07-deploy-file/01-deploy-file.md
> +For example, a deploy file includes another deploy file:
What deploy file is included? What is the location? Can I create a custom one? Where should I locate it?

2021-11-30 13:29 UTC, alexanderM91 commented on docs/07-deploy-file/01-deploy-file.md
> +The included deploy file includes more deploy files:
An example shows predefined docker/sdk templates.
If you want to create yours, please follow steps....

2021-11-30 13:29 UTC, alexanderM91 commented on docs/07-deploy-file/02-deploy.file.reference.v1.md
> +If you include a deploy file, the included deploy file is merged with the original one. The final deploy file is used to build the application. You can find it at `/{DOCKER_SDK_DIRECTORY}/deployment/
Maybe it's better to use docker/sdk config which will output to the customer the whole deploy file and if it has an error, point it out.

2021-11-30 13:29 UTC, alexanderM91 commented on docs/07-deploy-file/02-deploy.file.reference.v1.md
> +* `{deploy_file_name}: parameters:` - defines the [dynamic parameters](/01-deploy-file.md#dynamic-parameters) to be used when parsing the included deploy file. In the included deploy file, the parame
Can we extend an example or point to anchor from the another document with '%'.

2021-11-30 13:29 UTC, alexanderM91 commented on docs/07-deploy-file/03-common-cases-using-deploy-file-inheritance.md
> +We have two environments with the same deploy file structure. One thing is different - domain.
@andriitserkovnyi can we rephrase it? Or it wasn't reviewed?

2021-12-06 09:52 UTC, andriitserkovnyi commented on docs/07-deploy-file/01-deploy-file.md
> +The included deploy file includes more deploy files:
We are explaining a concept of dynamic parameters in this section, so no extra information. The location of templates is described further in the document.

2021-12-06 09:53 UTC, andriitserkovnyi commented on docs/07-deploy-file/02-deploy.file.reference.v1.md
> +* `{deploy_file_name}: parameters:` - defines the [dynamic parameters](/01-deploy-file.md#dynamic-parameters) to be used when parsing the included deploy file. In the included deploy file, the parame
We provided a link to the document where dynamic paratemeters are described. If the information in this section is not sufficient, a reader can always follow the link

2021-12-09 08:29 UTC, alexanderM91 commented on docs/07-deploy-file/01-deploy-file.md
> +To check how the final deploy file looks without stopping containers, run `docker config {DEPLOY_FILE_NAME}`. For example, if your main deploy file is `deploy.dev.yml`, run `docker config deploy.dev.
docker/sdk config

2021-12-09 08:36 UTC, alexanderM91 approved these changes

2021-12-13 08:07 UTC, merged