Improve documentation for using tideways
spryker/docker-sdk pull request #260
Opened 2021-11-17 14:28 UTC by alfredbez

### Description

- Ticket/Issue: I don't have access to your Jira instance and there is no issue on github as far as I know for this, I just [asked in the Spryker slack](https://sprykercommunity.slack.com/archives/CMYFJCG2E/p1636561124026400)

I was not able to get tideways running locally with the given instruction, because you need to set an ini setting so that your PHP containers can actually connect to the tideways container. Settings the environment does also not work and I'm not 100% sure this change made it work in the end. We use the env-variable `TIDEWAYS_ENVIRONMENT` in the [Dockerfile](https://github.com/spryker/docker-sdk/blob/0ecbcc7767a0e97de5e8bdab8f51b25189860393/images/common/services/tideways/Dockerfile#L4), so I changed `TIDEWAYS_ENVIRONMENT_NAME` to `TIDEWAYS_ENVIRONMENT` where I found that.

#### Related resources

- [Tideways documentation - Install in Docker With Compose](https://support.tideways.com/documentation/setup/installation/docker-with-compose.html)

#### Change log

- Adapt documentation on how to use tideways with the docker-sdk
- Changed default tideways environment name from `production` to `development`
- Read tideways environment name from `TIDEWAYS_ENVIRONMENT` instead of `TIDEWAYS_ENVIRONMENT_NAME`

### Checklist
- [x] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2021-11-26 13:50 UTC, alexanderM91 commented
Hi @alfredbez, thanks a lot for your contributions.
We will definitely investigate the possibility to set up Tideways locally according to your suggestions.

2022-04-10 12:39 UTC, alexanderM91 requested changes

2022-04-10 12:39 UTC, alexanderM91 commented on generator/src/templates/service/tideways/tideways.bash.twig
> -export TIDEWAYS_ENVIRONMENT_NAME=${TIDEWAYS_ENVIRONMENT_NAME:-"{{ services['tideways']['environment-name'] | default('production') }}"}
What is the purpose of renamed service property from `environment-name` to `environment`?
As to me we have to leave it without changes as it will cause as BC-break.

2022-04-10 12:39 UTC, alexanderM91 commented on docs/06-configuring-services.md
> +
Hi @zyuzka,
it seems to me that the main problem in the lack of the documentation. 
Could you please extend the documentation with necessary information?
Thank you.

2022-04-11 11:08 UTC, alfredbez commented on generator/src/templates/service/tideways/tideways.bash.twig
> -export TIDEWAYS_ENVIRONMENT_NAME=${TIDEWAYS_ENVIRONMENT_NAME:-"{{ services['tideways']['environment-name'] | default('production') }}"}
The problem is basically, that we sometimes use `TIDEWAYS_ENVIRONMENT_NAME` and sometimes only `TIDEWAYS_ENVIRONMENT`, so I decided to streamline that because it was not possible to change the name of the environment otherwise. I suspect, that we mixed those arguments up somewhere in the build process.

2022-04-11 12:07 UTC, alexanderM91 commented on generator/src/templates/service/tideways/tideways.bash.twig
> -export TIDEWAYS_ENVIRONMENT_NAME=${TIDEWAYS_ENVIRONMENT_NAME:-"{{ services['tideways']['environment-name'] | default('production') }}"}
We will check it out. Thank you.

2022-04-27 15:22 UTC, alexanderM91 commented on docs/06-configuring-services.md
> +
Hey @alfredbez,
could you please configure it one more type following public documentation?

2022-05-04 08:47 UTC, alfredbez commented on docs/06-configuring-services.md
> +
Hello @alexanderM91, I fear that I don't have time for this, since we're not sure if we will use the docker-sdk in the future at all. Feel free to close this PR

2022-05-04 08:49 UTC, closed without merging