[WIP] Several improvements + handle OPTIONS query nginx
spryker/docker-sdk pull request #266
Opened 2021-12-13 14:02 UTC by RodinVasily

### Description

- Increasing request time
- Database dependency for GLUE
- CORS headers for Zed container
- https://spryker.atlassian.net/browse/AL2021-1081 - Preflight OPTIONS requests in Nginx

### Checklist
- [x] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2021-12-13 15:38 UTC, alexanderM91 requested changes

2021-12-13 15:38 UTC, alexanderM91 commented on generator/src/templates/nginx/http/glue.server.conf.twig
> +            add_header 'Access-Control-Allow-Headers' '{{ endpointData['cors-allow-headers'] | default('') | nginx_var }}' always;
Is it the custom one `cors-allow-headers`?

2021-12-14 10:44 UTC, RodinVasily commented on generator/src/templates/nginx/http/glue.server.conf.twig
> +            add_header 'Access-Control-Allow-Headers' '{{ endpointData['cors-allow-headers'] | default('') | nginx_var }}' always;
yes, this is a custom field in `deploy.yml` file, just like `cors-allow-origin`

2021-12-17 10:24 UTC, alexanderM91 commented
Hi @RodinVasily, 
JFYI: GlueBackend support has been released.

2022-02-08 14:27 UTC, profuel commented on generator/src/templates/application/glue.yml.twig
> +      - database
@alexanderM91 do you have any updates about aforementioned new approach?

2022-02-08 14:29 UTC, profuel commented on generator/src/templates/nginx/http/zed.server.conf.twig
> +{% if endpointData['cors-allow-origin'] is not empty %}
this is/was a workaround to allow CORS for Zed container, which is used by Glue Backend,

2022-02-08 15:44 UTC, alexanderM91 commented on generator/src/templates/application/glue.yml.twig
> +      - database
Hi @profuel, yes it was released and ready for usage from the DockerSDK side starting from https://github.com/spryker/docker-sdk/compare/1.43.0...1.44.0

2022-10-07 12:04 UTC, closed without merging