SC-9516: Configure NPM and Node version from deploy.*.yaml
spryker/docker-sdk pull request #337
Opened 2022-06-16 15:41 UTC by zyuzka

### Description

- Ticket/Issue: https://spryker.atlassian.net/browse/SC-9516

#### Change log

- adjusted deploy file for configuration NodeJS version
- adjusted deploy file for configuration Npm version
- adjusted deploy file for configuration distribution of Node image
- adjusted docs

### Checklist
- [x] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2022-06-20 08:41 UTC, alexanderM91 requested changes

2022-06-20 08:41 UTC, alexanderM91 commented on generator/deploy-file-generator/config/validation.yml
> +image.node.distro:
Is it possible to have `in` condition?

2022-06-20 08:41 UTC, alexanderM91 commented on generator/deploy-file-generator/config/validation.yml
> +    range-value:
Can you please explain to me, why do we need rage filter here?

2022-06-20 08:41 UTC, alexanderM91 commented on generator/index.php
> +        SPRYKER_NODE_IMAGE_DISTRO_ENV_NAME => getNodeDistroName($projectData),
Is it possible to determine linux distribution dynamically?

2022-06-20 11:29 UTC, zyuzka commented on generator/deploy-file-generator/config/validation.yml
> +    range-value:
If we use a range filter with one argument it means we have only minimal value

2022-06-20 12:31 UTC, zyuzka commented on generator/index.php
> +        SPRYKER_NODE_IMAGE_DISTRO_ENV_NAME => getNodeDistroName($projectData),
Fixed

2022-06-20 13:17 UTC, alexanderM91 requested changes

2022-06-20 13:17 UTC, alexanderM91 commented on docs/07-deploy-file/02-deploy.file.reference.v1.md
> +* `image: node: distro:` - (optional)defines Linux distribution for Node Docker image. Value should be equal to your base PHP image. Default value is `alpine`. Possible value you can find on an offic
Hi,
do we need this configuration option?

2022-06-20 13:17 UTC, alexanderM91 commented on generator/index.php
> +const DEBIAN_DISTRO_NAME = 'bullseye';
What about buster?
Does it the same?

2022-06-21 08:40 UTC, zyuzka commented on docs/07-deploy-file/02-deploy.file.reference.v1.md
> +* `image: node: distro:` - (optional)defines Linux distribution for Node Docker image. Value should be equal to your base PHP image. Default value is `alpine`. Possible value you can find on an offic
Hi. For custom images

2022-06-21 09:20 UTC, alexanderM91 commented on docs/07-deploy-file/02-deploy.file.reference.v1.md
> +* `image: node: distro:` - (optional)defines Linux distribution for Node Docker image. Value should be equal to your base PHP image. Default value is `alpine`. Possible value you can find on an offic
Please, extend documentation with possible distro options.

2022-06-21 10:21 UTC, alexanderM91 approved these changes

2022-06-30 14:03 UTC, andriitserkovnyi approved these changes

2022-07-07 07:17 UTC, merged