782/fixed ds off install issues with jenkins
spryker/docker-sdk pull request #426
Opened 2023-03-23 12:49 UTC by geega

### Description

- Ticket/Issue:  https://spryker.atlassian.net/browse/FRW-1782

2023-03-23 21:26 UTC, yaroslav-spryker requested changes

2023-03-23 21:26 UTC, yaroslav-spryker commented on bin/service/scheduler/jenkins.sh
> +                SPRYKER_CURRENT_REGION=""
Looks like we should know the region from the store as well, we don't?

2023-03-24 14:57 UTC, geega commented on bin/service/scheduler/jenkins.sh
> +                SPRYKER_CURRENT_REGION=""
@yaroslav-spryker  No. This var should be empty for DS OFF. But only during install process this var have value.   When Composer:exec used SPRYKER_CURRENT_REGION for run command ad APPLICATION_REGION etc. 
And this env var used for set region for transfer for request to jenkins. Also fixed in PR https://github.com/spryker/spryker/pull/10044

2023-03-24 16:28 UTC, yaroslav-spryker approved these changes

2023-03-31 15:21 UTC, eduard-melnytskyi commented
Closed becasue same changes were alrady applied to the target branch

2023-03-31 15:21 UTC, closed without merging