WIP: SC-16584: Update of swagger-ui image and Glue Infrastructure preparation
spryker/docker-sdk pull request #468
Opened 2023-10-10 05:54 UTC by fsmeier

### Description

- Ticket/Issue: [SC-16584](https://spryker.atlassian.net/browse/SC-16584)

As a developer I want to see my RESTful API schema not only for the Old Glue API but also for the new Glue API infrastructure (Glue Storefront API & Glue Backend API). I want to be able to use the same tooling but select different schemas based on my environment configuration.

#### Change log

- Update of swagger-ui to v5.9.0
- Integration of new Glue Infrastructure to swagger-ui

### Checklist
- [x] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2023-12-26 16:51 UTC, zyuzka requested changes

2023-12-26 16:51 UTC, zyuzka commented on generator/src/templates/service/swagger-ui/v5.9/swagger-ui.yml.twig
> +            {% if firstEndpointMap['glue'] is defined  %}{ url: \"{{ protocol ~ firstEndpointMap['glue'] }}/schema.yml\", name: \"(Old) Glue API\" },\{% endif %}
Mb better move logic into the index.php file and provide mapped data in template

2023-12-26 16:51 UTC, zyuzka commented on generator/src/templates/service/swagger-ui/v5.9/swagger-ui.yml.twig
> +
empty lines

2023-12-26 16:51 UTC, zyuzka commented on generator/src/templates/service/swagger-ui/v5.9/swagger-ui.yml.twig
> +            {% if firstEndpointMap['glue'] is defined  %}{ url: \"{{ protocol ~ firstEndpointMap['glue'] }}/schema.yml\", name: \"(Old) Glue API\" },\{% endif %}
Is the old Swagger version supported URLS env variable? If yes, we need to adjust both templates

2023-12-26 16:51 UTC, zyuzka commented on generator/src/templates/nginx/http/gateway/glue-storefront.server.conf.twig
> +    proxy_set_header Host $host;
Move the template to a separate file and include it with $cli_proxy_pass

2023-12-26 16:51 UTC, zyuzka commented on bin/standalone/cli-rpc.js
> +    _get_glueBackendSchema(request, response) {
As I see - all Glue* methods are the same. Why do we copy-paste all of them?

2023-12-26 18:42 UTC, zyuzka approved these changes

2024-01-08 07:39 UTC, alexanderM91 approved these changes

2024-01-08 07:40 UTC, merged